### ISSUE TITLE
Hiding wrappers from directus filters

### ISSUE THREAD

**Issue by rafazafar** [ptkio/directus-extension-group-layout-sidebar#1]
Hi @ptkio
Thanks for the really useful extension!
What do you think about hiding the wrappers from appearing in filters in directus?
Sadly im not versed enough about directus yet to help make PR for this yet.

Currently the columns in wrappers would be nested 2 deep, which makes it harder for people to use the filters.
Data Studio:
<img width="346" alt="Screenshot 2024-05-11 at 9 49 59 PM" src="https://github.com/ptkio/directus-extension-group-layout-sidebar/assets/22354051/e9197c3a-e9e7-470b-86b8-daf2482221ca">

Access Control > Item Permission
<img width="421" alt="Screenshot 2024-05-11 at 9 52 36 PM" src="https://github.com/ptkio/directus-extension-group-layout-sidebar/assets/22354051/51654472-3d9f-4f00-9302-92cf8c342dc7">

Wondering if its even possible to make the nested columns/fields flat at top level.
Please pardon my bad field naming 🤭

**Comment by ptkio** [comment]
Hi @rafazafar !
Thanks for the feedback !

I have exactly the same issue and it's really annoying!
Unfortunately, the created groups respond to the functioning of Directus groups, which seem to have the same problem. To resolve this issue, it would be necessary to go deeper and add an option that allows groups to be "invisible" in these interfaces. It doesn't seem like such an option exists at this time. This addition needs to be made directly in Directus.
Unfortunately, there's nothing I can do on my side.

If anyone has a solution, I'm interested, but I don't see one without modifying the Directus source. Maybe a request could be made directly to Directus?
But I'm not sure if they would consider it, as it's a rather specific issue, and responding to every such request might complicate the source.

**Comment by ptkio** [comment]
The issue is resolved in the latest Directus version. It's not the best way to navigate the data, but it's the only solution to apply a layout without breaking other functionality or requiring extensive development.
