### ISSUE TITLE
Floating header

### ISSUE THREAD

**Issue by bvasya** [ptkio/directus-extension-group-layout-sidebar#3]
The sidebar is now floating when scrolling. It would be useful to add an option to make the header float when scrolling. Or make a separate “Floating top” section

**Comment by ptkio** [comment]
Hi bvasya,

Thanks for the request.

I apologize for the delayed response; I'm currently working on another project.

I'm not sure it's a good idea to add another floating header to the page as it will take up too much space. Additionally, I don't have the time to do it right now.

Feel free to fork my extension if you'd like to make the changes yourself.
